language: node_js

sudo: false

addons:
  apt:
    packages:
      - xvfb
      - gnome-keyring
      - libgnome-keyring-dev


node_js:
  - "0.11"
  - "0.10"
  - "iojs"

notifications:
  email: false

script: xvfb-run ./script/cibuild

git:
  depth: 10

branches:
  only:
    - master
